runtime: nodejs22
env: standard

instance_class: F2
entrypoint: npm start

env_variables: 
  DATABASE_URL: "postgresql://postgres:postgres@/postgres?sslmode=require" 
  CLOUD_SQL_CONNECTION_NAME: "task-manager-446820:me-west1:taskmanager11" 

beta_settings: 
  cloud_sql_instances: "${CLOUD_SQL_CONNECTION_NAME}"